name: Updates README data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Run script
        run: python main.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"
          
          git add -A
          
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README- $(date +'%d/%m/%Y')"
          
          git push
